### ISSUE TITLE
Minify all possible files in install pack?

### ISSUE THREAD

**Issue by EPTamminga** [dnnconsulting/DnnC.Bootster#11]
Is it an option to minify/compress all possible files (.css, .js, png, jpg) in the install pack? So you always have the minimal file sizes for execution?

**Comment by dnnconsulting** [comment]
This is a good point, I have used a couple of .min css and .js files in the theme which are included but I seam to have missed a couple of them. On the other hand I wanted the main css and js files (bootster.css and booster.js for example) to be readable for beginners to easily read them so that they can change and experiment with the skin.

Another option is to create a second install package for advanced users, then with all files/media minified and optimized, and to also remove all of the 'include' files out and incorporated into the skins directly.

I'll try and plan this in as soon as I can for you and others.

**Comment by EPTamminga** [comment]
The packaging should be an automated build process, otherwise one will forget to do it on a release. Any idea how to do that? Can I help? An option could be to use SASS or LESS for the .css manipulation? 

OTOH, is a seperate full/unminfied install needed? The repo contains all original files, and if the install package is created automagically, there is no need for a separate uncompressed install version?

I already did some optimization on the images, there is no loss in there. I will create a PR for those.

**Comment by david-poindexter** [comment]
@EPTamminga I agree.  The source can be full/unminified versions of the CSS/JS.  The build process can take care of the minification, etc.  Furthermore, the build process can/should create an Install package (with minified CSS/JS) as well as a Source package (with unminified versions of the CSS/JS).

**Comment by EPTamminga** [comment]
@nvisionative Do you have a build process available to implement this? 
We have created a build process for DNN modules that does a similar thing, but for module package build, including js and css minification and this has been very beneficial for development.

**Comment by david-poindexter** [comment]
Same here @EPTamminga - we have this for module dev, but have not done this for a theme project.  I am assuming it would be very similar, but I currently do not have the bandwidth to work on this.

**Comment by dnnconsulting** [comment]
@EPTamminga, @nvisionative your changes have been committed. I still need to change the css and js to minified though. On my todo list

**Comment by EPTamminga** [comment]
We really should work on an automated way of doing the minification & packaging of theme packs. Otherwise we create work for ourselves which is prone to omissions and errors.

**Comment by EPTamminga** [comment]
Closing the issue. Packaging and minification can be new issue.
