### ISSUE TITLE
dutch language pack breaks skin 

### ISSUE THREAD

**Issue by schotman** [dnnconsulting/DnnC.Bootster#15]
The size of the buttons and tabs are too big
![issues booster](https://cloud.githubusercontent.com/assets/2582737/19592622/e90707f2-977c-11e6-922d-20d01e48a869.jpg)

Solved by:
ul.dnnAdminTabNav li a {
    font-size: 14px;
}

.ControlContainer {
    width: 900px;
}
would fit.

**Comment by dnnconsulting** [comment]
Hi again Peter,

I think this is caused by a small piece of code I used by David Poindexter found in the .css for the skins:

`/* Make the Control bar more mobile friendly */
.ControlContainer {
    position: relative;
    width: 727px;
    height: 53px;
    margin: 0px auto;
}`

I think, if you remove this it would solve allot.

If not maybe you could submit a pull request so that I can merge your changes.

Regards,

Geoff.
